import { TILE_SIZE, type WorldSnapshot } from '@/world/engine/types'

/** Ambient flower frames (2-frame sway), generated by scripts/gen-flowers.cjs. */
const FLOWER_FRAMES = ['/assets/maps/flower_0.png', '/assets/maps/flower_1.png']

/**
 * Animated Flower Layer - small swaying flower tufts on the ground.
 *
 * Draws a 2-frame flower at each tile the map lists in `flowerTiles`, cycled by the
 * engine's ambient `animTick` so foliage moves even while the player stands still (like
 * the water shimmer). Sits below entities - flowers are ground decor the player passes
 * over. Purely decorative (aria-hidden) and a pure snapshot consumer.
 */
export function AnimatedFlowerLayer({ snapshot }: { snapshot: WorldSnapshot }) {
  const tiles = snapshot.flowerTiles
  if (tiles.length === 0) return null
  const src = FLOWER_FRAMES[snapshot.animTick % FLOWER_FRAMES.length]

  return (
    <>
      {tiles.map((t) => (
        <img
          key={`${t.x},${t.y}`}
          aria-hidden
          src={src}
          alt=""
          draggable={false}
          className="pointer-events-none absolute left-0 top-0 max-w-none [image-rendering:pixelated]"
          style={{
            width: TILE_SIZE,
            height: TILE_SIZE,
            transform: `translate3d(${t.x * TILE_SIZE}px, ${t.y * TILE_SIZE}px, 0)`,
          }}
        />
      ))}
    </>
  )
}
