import type { TileCoord } from '@/world/engine/types'
import type { WorldEntity } from '@/world/entities/entityTypes'

/**
 * A fully data-driven map definition. Everything the engine needs to run a map lives
 * here - art, walkability, entities, spawn, music, and step-triggered audio zones.
 * Creating a new area = adding one of these objects to the map registry. No behavior
 * is ever hardcoded against a specific map.
 */

/** A step-triggered audio zone: music loops while the player stands inside the rect. */
export interface AudioZone {
  id: string
  rect: { x: number; y: number; width: number; height: number }
  track: string
}

/**
 * One image layer of the scene, drawn full-map-size. Layers stack in array order.
 * `role` documents intent (ground/terrain/roads for background; treetops/roofs/bridges/
 * canopies for foreground) and can drive per-role treatment later; it doesn't change
 * how the image is drawn today.
 */
export interface SceneLayer {
  src: string
  role?: 'ground' | 'terrain' | 'roads' | 'treetops' | 'roofs' | 'bridges' | 'canopies' | 'decor'
  alt?: string
}

export interface MapData {
  id: string
  name: string
  /** Grid dimensions in tiles. */
  width: number
  height: number
  /** Where the player appears when entering with no explicit spawn. */
  spawn: TileCoord
  /** Background artwork drawn under everything (the real town/interior image). */
  background: string
  /**
   * Optional foreground artwork drawn OVER entities (tree-tops, roofs, canopies) so the
   * player passes behind it. Same dimensions as the background; transparent elsewhere.
   */
  foreground?: string
  /**
   * Optional MULTI-layer art. When present, these stack (in order) instead of / in
   * addition to the flat `background`/`foreground`. This is how the Background Layer's
   * ground→terrain→roads and the Foreground Layer's treetops→roofs→bridges→canopies are
   * expressed for maps that ship separated art. Flat single images remain fully valid.
   */
  backgroundLayers?: SceneLayer[]
  foregroundLayers?: SceneLayer[]
  /** rows of `#` (blocked) / `.` (walkable), one char per tile. */
  collision: string[]
  /**
   * Optional ordered animated water frames (full-map-size, transparent except water tiles),
   * cycled by the engine's ambient animation tick so open water shimmers. Generated by
   * scripts/gen-cerulean-water.cjs. Drawn just above the background.
   */
  waterFrames?: string[]
  /**
   * Optional ambient flower tiles: tile coords where a small 2-frame swaying flower tuft
   * is drawn (generated by scripts/gen-flowers.cjs), cycled by the engine's animTick so
   * foliage moves even while idle. Purely decorative; does not affect collision.
   */
  flowerTiles?: TileCoord[]
  /** Everything interactive/steppable on the map. */
  entities: WorldEntity[]
  /** Optional per-map audio zones. */
  audioZones?: AudioZone[]
  /** Optional default music for the whole map. */
  music?: string
}

/** The map registry type: id → data. Populated in world/maps. */
export type MapRegistry = Record<string, MapData>
